---
# Copyright (c) 2025 Gravitino LLC
# MIT License

- name: restart openssh
  ansible.builtin.systemd:
    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
    state: restarted
  become: true
